export const SIGNUP_SUCCESS = 'REGISTER_SUCCESS';
export const SIGNUP_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_FAIL = 'UPDATE_PASSWORD_FAIL';
export const UPDATE_DETAIL_SUCCESS = 'UPDATE_DETAIL_SUCCESS';
export const UPDATE_DETAIL_FAIL = 'UPDATE_DETAIL_FAIL';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';
export const LOGOUT = 'LOGOUT';

export const FACILITIES_LOADED = 'FACILITIES_LOADED';
export const FACILITIES_ERROR = 'FACILITIES_ERROR';
export const FACILITY_LOADED = 'FACILITY_LOADED';
export const FACILITY_ERROR = 'FACILITY_ERROR';
export const CLEAR_FACILITY = 'CLEAR_FACILITY';
export const CLEAR_FACILITIES = 'CLEAR_FACILITIES';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAIL = 'SEARCH_FAIL';
export const TOP_FACILITIES_LOADED = 'TOP_FACILITIES_LOADED';
export const TOP_FACILITIES_ERROR = 'TOP_FACILITIES_ERROR';

export const REVIEWS_LOADED = 'REVIEWS_LOADED';
export const REVIEWS_ERROR = 'REVIEWS_ERROR';
export const CLEAR_REVIEWS = 'CLEAR_REVIEWS';
export const CLEAR_REVIEWS_ERRORS = 'CLEAR_REVIEWS_ERRORS';
export const ADD_REVIEW_FAIL = 'ADD_REVIEW_FAIL';
export const UPDATE_REVIEW_FAIL = 'UPDATE_REVIEW_FAIL';
export const DELETE_REVIEW_FAIL = 'DELETE_REVIEW_FAIL';

export const ROOM_LOADED = 'ROOM_LOADED';
export const ROOM_LOADED_ERROR = 'ROOM_LOADED_ERROR';
export const CLEAR_ROOM = 'CLEAR_ROOM';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
